### ISSUE TITLE
Missing spaces / punctuations

### ISSUE THREAD

**Issue by LeeTZ** [J-Miao/J-Miao.github.io#7]
On http://www.miaozhengjie.com/publication/cidr17/ , in the abstract:

> ... that are tailored to domainspecific analyses, or manually design, implement...

Seems missing a space or a dash between 'domain' and 'specific'

> ... and (d)techniques to synthesize interactive interfaces tailored to end-users.

Seems missing a space right after (d).

**Comment by J-Miao** [comment]
b279f4
