### ISSUE TITLE
Bad Facebook sharing links

### ISSUE THREAD

**Issue by LeeTZ** [J-Miao/J-Miao.github.io#8]
On paper detail pages, the sharing link for Facebook is actually broken because the path passed to 'u' param on https://www.facebook.com/sharer.php should not be a relative path.

Should add hostname as: 
https://www.facebook.com/sharer.php?u=www.miaozhengjie.com%2fpublication%2fcidr17%2f
instead.

**Comment by J-Miao** [comment]
b279f4
