### ISSUE TITLE
Bad parameters for 'mailto'

### ISSUE THREAD

**Issue by LeeTZ** [J-Miao/J-Miao.github.io#9]
On paper detail pages, the link of 'mail to'  is bad.
If you would like to use this as a sharing button, then in the text, a full path should be provided, i.e. http://www.miaozhengjie.com/publication/cidr17/. It's a relative path for now.
And furthermore, if the motivation of this button is for you to receive feedbacks, then the 'to' option should be set to J-Miao's email.

**Comment by J-Miao** [comment]
b279f4
